# Generated by Django 5.2.4 on 2025-07-29 07:22

import django.db.models.deletion
import django.utils.timezone
import osg_project.file_manager_app.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Filing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_reference', models.CharField(help_text='Unique reference number for the filing (e.g., OSG/FIL/2023/001).', max_length=255, unique=True, verbose_name='File Reference')),
                ('file_name', models.CharField(help_text="A descriptive name for the filing (e.g., 'Case of John Doe vs. State').", max_length=255, verbose_name='File Name')),
                ('serial_number', models.CharField(help_text='Unique serial number for the filing.', max_length=100, unique=True, verbose_name='Serial Number')),
                ('receiving_department', models.CharField(help_text='The department receiving the filing (e.g., Litigation, Advisory).', max_length=255, verbose_name='Receiving Department')),
                ('receiving_date', models.DateField(help_text='The date the filing was received.', verbose_name='Receiving Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time the filing record was created in the system.', verbose_name='Date Created')),
                ('scanned_copy', models.FileField(blank=True, help_text='Upload a main scanned PDF copy of the filing (Max 5MB).', null=True, upload_to='filings_main_scans/', validators=[osg_project.file_manager_app.models.validate_pdf], verbose_name='Main Scanned Copy (PDF)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receiving_officer', models.ForeignKey(blank=True, help_text='The officer responsible for this filing.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filings_received', to=settings.AUTH_USER_MODEL, verbose_name='Receiving Officer')),
            ],
            options={
                'verbose_name': 'Filing',
                'verbose_name_plural': 'Filings',
                'ordering': ['-receiving_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FilingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(help_text="A descriptive name for the document (e.g., 'Financial Report', 'Witness List').", max_length=255)),
                ('folio_number', models.CharField(blank=True, help_text='Optional folio number for the document.', max_length=100, null=True)),
                ('uploaded_file', models.FileField(help_text='Upload the document (CSV or Excel format, Max 10MB).', upload_to='filing_docs/', validators=[osg_project.file_manager_app.models.validate_csv_excel])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('filing', models.ForeignKey(help_text='The filing this document belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='file_manager_app.filing')),
            ],
        ),
        migrations.CreateModel(
            name='IncomingLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_date', models.DateField(default=django.utils.timezone.now, help_text='The date the letter was received by the office.', verbose_name='Date Received')),
                ('serial_number', models.CharField(help_text='Unique serial number assigned upon receipt.', max_length=50, unique=True, verbose_name='Serial No.')),
                ('date_of_letter', models.DateField(help_text='The date written on the letter itself.', verbose_name='Date of Letter')),
                ('reference', models.CharField(help_text='The reference number of the incoming letter.', max_length=100, unique=True, verbose_name='Reference No.')),
                ('subject', models.CharField(help_text='The subject line of the letter.', max_length=255, verbose_name='Subject')),
                ('author', models.CharField(help_text='The name of the person or entity who sent the letter.', max_length=100, verbose_name='Author/Sender')),
                ('remarks', models.TextField(blank=True, help_text='Any additional remarks or notes about the letter.', verbose_name='Remarks')),
                ('scanned_copy', models.FileField(blank=True, help_text='Upload a scanned PDF copy of the incoming letter (Max 5MB).', null=True, upload_to='incoming_letters_scans/', validators=[osg_project.file_manager_app.models.validate_pdf], verbose_name='Scanned Copy (PDF)')),
                ('signed_at', models.DateField(blank=True, help_text='Date the letter was signed off.', null=True)),
                ('signature', models.ImageField(blank=True, help_text='Digital signature (if applicable).', null=True, upload_to='signatures/')),
                ('sender', models.CharField(blank=True, help_text='Full name or organization of the sender (redundant with author, but kept from example).', max_length=255, null=True)),
                ('is_actioned', models.BooleanField(default=False, help_text='Indicates if the letter has been actioned or processed.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receiving_officer', models.ForeignKey(blank=True, help_text='The officer responsible for handling this letter.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_letters_received', to=settings.AUTH_USER_MODEL, verbose_name='Receiving Officer')),
                ('signed_by', models.ForeignKey(blank=True, help_text="The user who signed off on this letter's action.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_letters_signed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Incoming Letter',
                'verbose_name_plural': 'Incoming Letters',
                'ordering': ['-received_date', '-serial_number'],
            },
        ),
        migrations.CreateModel(
            name='OutgoingLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_sent', models.DateField(default=django.utils.timezone.now, help_text='The date the letter was dispatched.', verbose_name='Date Sent')),
                ('serial_number', models.CharField(help_text='Unique serial number assigned upon dispatch.', max_length=50, unique=True, verbose_name='Serial No.')),
                ('reference', models.CharField(help_text='The reference number of the outgoing letter.', max_length=100, unique=True, verbose_name='Reference No.')),
                ('subject', models.CharField(help_text='The subject line of the letter.', max_length=255, verbose_name='Subject')),
                ('recipient', models.CharField(help_text='The name of the person or entity receiving the letter.', max_length=255, verbose_name='Recipient')),
                ('scanned_copy', models.FileField(blank=True, help_text='Upload a scanned PDF copy of the outgoing letter (Max 5MB).', null=True, upload_to='outgoing_letters_scans/', validators=[osg_project.file_manager_app.models.validate_pdf], verbose_name='Scanned Copy (PDF)')),
                ('remarks', models.TextField(blank=True, help_text='Any additional remarks or notes about the letter.', verbose_name='Remarks')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sent_by', models.ForeignKey(blank=True, help_text='The officer who dispatched this letter.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoing_letters_sent', to=settings.AUTH_USER_MODEL, verbose_name='Sent By Officer')),
            ],
            options={
                'verbose_name': 'Outgoing Letter',
                'verbose_name_plural': 'Outgoing Letters',
                'ordering': ['-date_sent', '-serial_number'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('officer', 'Officer'), ('superuser', 'Superuser')], default='officer', help_text='The role of the user within the system (Officer or Superuser).', max_length=10)),
                ('employee_number', models.CharField(help_text='Unique employee identification number.', max_length=50, unique=True)),
                ('profile_picture', models.ImageField(blank=True, help_text='Optional profile picture for the user.', null=True, upload_to='profile_pics/')),
                ('user', models.OneToOneField(help_text='The associated Django User account.', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
