# Generated by Django 5.2.4 on 2025-08-01 10:21

import osg_project.file_manager_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filingdocument',
            name='uploaded_file',
            field=models.FileField(help_text='Upload the document (PDF or Word format, Max 10MB).', upload_to='filing_docs/', validators=[osg_project.file_manager_app.models.validate_pdf_word]),
        ),
    ]
