# Generated by Django 5.2.4 on 2025-08-05 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager_app', '0002_alter_filingdocument_uploaded_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='outgoingletter',
            name='receipt_file',
            field=models.FileField(blank=True, null=True, upload_to='outgoing_receipts/'),
        ),
        migrations.AlterField(
            model_name='outgoingletter',
            name='scanned_copy',
            field=models.FileField(blank=True, null=True, upload_to='outgoing_letters/'),
        ),
    ]
