# Generated by Django 5.2.4 on 2025-08-11 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager_app', '0003_outgoingletter_receipt_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('incoming', 'Incoming Letter'), ('outgoing', 'Outgoing Letter'), ('filing', 'Filing Document')], help_text='The category of the archived file.', max_length=20)),
                ('original_name', models.CharField(help_text='The original name of the file before archiving.', max_length=255)),
                ('archived_name', models.CharField(help_text='The name of the file in the archive storage.', max_length=255)),
                ('archived_date', models.DateTimeField(auto_now_add=True, help_text='The date and time when the file was archived.')),
                ('reference', models.CharField(blank=True, help_text='Optional reference number associated with the file.', max_length=255)),
                ('subject', models.CharField(blank=True, help_text='Optional subject or title of the file.', max_length=255)),
                ('extra_info', models.TextField(blank=True, help_text='Any extra information or notes about the archived file.')),
                ('restored', models.BooleanField(default=False, help_text='Indicates if the file has been restored from the archive.')),
            ],
            options={
                'verbose_name': 'Archived File',
                'verbose_name_plural': 'Archived Files',
                'ordering': ['-archived_date'],
            },
        ),
    ]
